/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Net.Thrift
{
  public enum LoginType
  {
    USER_GUEST = 1,
    USER_ACCOUNT = 2,
    USER_THIRDPARTY = 3,
  }
}
