/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Net.Thrift
{
  public enum PeerType
  {
    PEER_TYPE_MASTER = 1,
    PEER_TYPE_ACCOUNT = 5,
    PEER_TYPE_GAME = 10,
    PEER_TYPE_CLIENT = 15,
    PEER_TYPE_DEFAULT = 20,
  }
}
