/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Net.Thrift
{
  public enum SerializeType
  {
    SERIALIZE_TYPE_THRIFT = 1,
    SERIALIZE_TYPE_PROTOBUFFER = 2,
  }
}
