/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Net.Thrift
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class ResponseAuthServerPublicKey : TBase
  {
    private string _serverPubKey;

    public string ServerPubKey
    {
      get
      {
        return _serverPubKey;
      }
      set
      {
        __isset.serverPubKey = true;
        this._serverPubKey = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool serverPubKey;
    }

    public ResponseAuthServerPublicKey() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String) {
              ServerPubKey = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("ResponseAuthServerPublicKey");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (ServerPubKey != null && __isset.serverPubKey) {
        field.Name = "serverPubKey";
        field.Type = TType.String;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(ServerPubKey);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("ResponseAuthServerPublicKey(");
      bool __first = true;
      if (ServerPubKey != null && __isset.serverPubKey) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("ServerPubKey: ");
        __sb.Append(ServerPubKey);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
