/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Net.Thrift
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class ReuqestGameConnect : TBase
  {
    private string _gameserver;
    private int _sequenceId;
    private string _randomKey;

    public string Gameserver
    {
      get
      {
        return _gameserver;
      }
      set
      {
        __isset.gameserver = true;
        this._gameserver = value;
      }
    }

    public int Uid { get; set; }

    public int SequenceId
    {
      get
      {
        return _sequenceId;
      }
      set
      {
        __isset.sequenceId = true;
        this._sequenceId = value;
      }
    }

    public string RandomKey
    {
      get
      {
        return _randomKey;
      }
      set
      {
        __isset.randomKey = true;
        this._randomKey = value;
      }
    }

    public string Passport { get; set; }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool gameserver;
      public bool sequenceId;
      public bool randomKey;
    }

    public ReuqestGameConnect() {
    }

    public ReuqestGameConnect(int uid, string passport) : this() {
      this.Uid = uid;
      this.Passport = passport;
    }

    public void Read (TProtocol iprot)
    {
      bool isset_uid = false;
      bool isset_passport = false;
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String) {
              Gameserver = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I32) {
              Uid = iprot.ReadI32();
              isset_uid = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.I32) {
              SequenceId = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.String) {
              RandomKey = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 5:
            if (field.Type == TType.String) {
              Passport = iprot.ReadString();
              isset_passport = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
      if (!isset_uid)
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      if (!isset_passport)
        throw new TProtocolException(TProtocolException.INVALID_DATA);
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("ReuqestGameConnect");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (Gameserver != null && __isset.gameserver) {
        field.Name = "gameserver";
        field.Type = TType.String;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Gameserver);
        oprot.WriteFieldEnd();
      }
      field.Name = "uid";
      field.Type = TType.I32;
      field.ID = 2;
      oprot.WriteFieldBegin(field);
      oprot.WriteI32(Uid);
      oprot.WriteFieldEnd();
      if (__isset.sequenceId) {
        field.Name = "sequenceId";
        field.Type = TType.I32;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(SequenceId);
        oprot.WriteFieldEnd();
      }
      if (RandomKey != null && __isset.randomKey) {
        field.Name = "randomKey";
        field.Type = TType.String;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(RandomKey);
        oprot.WriteFieldEnd();
      }
      field.Name = "passport";
      field.Type = TType.String;
      field.ID = 5;
      oprot.WriteFieldBegin(field);
      oprot.WriteString(Passport);
      oprot.WriteFieldEnd();
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("ReuqestGameConnect(");
      bool __first = true;
      if (Gameserver != null && __isset.gameserver) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Gameserver: ");
        __sb.Append(Gameserver);
      }
      if(!__first) { __sb.Append(", "); }
      __sb.Append("Uid: ");
      __sb.Append(Uid);
      if (__isset.sequenceId) {
        __sb.Append(", SequenceId: ");
        __sb.Append(SequenceId);
      }
      if (RandomKey != null && __isset.randomKey) {
        __sb.Append(", RandomKey: ");
        __sb.Append(RandomKey);
      }
      __sb.Append(", Passport: ");
      __sb.Append(Passport);
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
